kind: pipeline
name: default

steps:
- name: build
  image: debian:stretch
  environment:
    DECRYPTKEY:
      from_secret: DECRYPTKEY
  commands:
  - .drone/install_packages
  - .drone/decrypt_keystore
  - .drone/install_android
  - .drone/build_app
