#! /bin/bash

# change to defined directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

gpg --decrypt --batch --passphrase $DECRYPTKEY release.keystore.gpg > ../release.keystore
gpg --decrypt --batch --passphrase $DECRYPTKEY gradle.properties.gpg > ~/.gradle/gradle.properties
gpg --decrypt --batch --passphrase $DECRYPTKEY trainer_deployment_key.json.gpg > ../trainer_deployment_key.json
