#! /usr/bin/env bash

set -e

export LANG=C.UTF-8

if [ ! -f build/outputs/apk/release/sbfs-trainer-release.apk ] ; then
    echo No release APK file found. Cannot deploy to Google Play.
    echo Content of build/outputs is:
    ls -R build/outputs
    exit 1
fi

fastlane supply -j trainer_deployment_key.json -p eu.wimmerinformatik.sbfs -b build/outputs/apk/release/sbfs-trainer-release.apk -a alpha || echo "Waiting for fastlane update in NixPkgs ... manual deployment needed!"
